name: CodeQL Analysis

on:
  push:
    branches: ["main", "releases/**"]
    paths:
      - "**/src"
    # paths-ignore:
    #   - "*README.md"
    #   - "docs/*"
    # paths:
    #   - "**.cs"
    #   - "**.csproj"
  pull_request:
    branches: ["main", "releases/**"]
    paths:
      - "**/src"
    # paths-ignore:
    #   - "*README.md"
    #   - "docs/*"

jobs:
  sdl_compliance:
    name: Running SDL Compliance Policy checks (CodeQL)
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    continue-on-error: true

    strategy:
      matrix:
        include:
          # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
          # Learn more about CodeQL language support at https://git.io/codeql-language-support
          # Analyzes C and C++ code using the commands in `Build C and C++ code`
          - language: "cpp"
            build-mode: manual # Or autobuild
            build-config: "Release"
            build-platform: "x64"

    env:
      msbuildPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
      sourceCodeDirectory: '$(Build.SourcesDirectory)\LogMonitor'
      BuildConfiguration: Release
      solution: "**/*.sln"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      # https://github.com/marketplace/actions/setup-msbuild#specifying-msbuild-architecture-optional
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{ matrix.build-platform }} # Default is x86. Options are x86, x64, and arm64

      # https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
      # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality # Default is "security-extended"
          build-mode: ${{ matrix.build-mode }}
          # querysuite: "code-scanning"
          # sourcesfolder: '$(Build.SourcesDirectory)\LogMonitor'
          # buildtype: Manual
          # ram: 8192

      # # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#building-cc
      # - name: Autobuild
      #   uses: github/codeql-action/autobuild@v3

      - name: Build app for release
        run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release

      # TODO: Add Makefile for C++ project
      # https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#arguments
      - name: Build LogMonitor
        run:  |
          msbuild.exe $(BUILD.SourcesDirectory)\$(solution) /t:clean
          msbuild.exe $(BUILD.SourcesDirectory)\$(solution) /p:platform=$(BuildPlatform) /p:configuration=$(BuildConfiguration)
        env:
          msbuildPath: ${{ env.msbuildPath }}
          solution: ${{ env.solution }}
          BuildPlatform: ${{ matrix.build-platform }}
          BuildConfiguration: ${{ env.BuildConfiguration }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload CodeQL Analysis Results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: codeql-results.sarif

